language: php
sudo: false
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
script: 'echo "No test specified";'
php:
  - '7.1'
before_install:
  - nvm install && nvm use
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
